### ISSUE TITLE
Ошибка при отображении истории снимка https://pastvu.com/p/893048

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#359]
Ошибка при отображении истории снимка https://pastvu.com/p/893048

![image](https://user-images.githubusercontent.com/60163100/114583594-6e9af100-9c8a-11eb-8de5-861ad2895aa8.png)

**Comment by kabalin** [comment]
```
socket.run "photo.giveObjHist" returned error
{type: "ApplicationError", code: "UNHANDLED_ERROR", message: "Error occurred on server", rid: "35fkxubz14"}
 ```
Нужно логи смотреть.

**Comment by kabalin** [comment]
```
app_1          | [2021-04-26 10:49:07.737] [ERROR] webapi-photo - [RID-otm8fiwead S-A9qbSK21hfi5] Error calling method "photo.giveObjHist" with params: { cid: 893048, fetchId: 1, showDiff: true }
app_1          |  TypeError: Cannot read property 'cid' of undefined
app_1          |     at Object.fillRegionsHash (/code/controllers/region.js:316:32)
app_1          |     at Object.giveObjHist (/code/controllers/photo.js:3735:39)
app_1          |     at runMicrotasks (<anonymous>)
app_1          |     at processTicksAndRejections (node:internal/process/task_queues:93:5)
app_1          |     at async Object.callMethod [as call] (/code/app/webapi/server.js:85:62)
app_1          |     at async Object.callWebApi (/code/app/request.js:122:15)
app_1          |     at async handleSocketRequest (/code/app/request.js:382:20)
app_1          | [2021-04-26 10:49:07.740] [INFO] request - [RID-otm8fiwead S-A9qbSK21hfi5] <- Socket request for "photo.giveObjHist" method finished in 16ms and responded to the client
```

**Comment by mkgrgis** [comment]
Регион не проставлен или отвалился? Нарушение работы коллекции при сбое?

**Comment by kabalin** [comment]
> Регион не проставлен или отвалился?
Был удален, а в истории изменений сохранился.

**Comment by paul-k-pastvu** [comment]
Коллеги @kabalin и @aeifn  - я смотрю, что баг закрыт, а проблема-то осталась. Как так?

**Comment by aeifn** [comment]
> Коллеги @kabalin и @aeifn - я смотрю, что баг закрыт, а проблема-то осталась. Как так?

мы не выпускали версию с этим багфиксом
