### ISSUE TITLE
Error when viewing map at low zoom levels with year condition / Ошибка при просмотре карты на небольшом зуме с ограничением по году

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#653]
When viewing map at low zoom levels with years restrictions:
```
[2023-12-27T22:03:53.652] [INFO] request - [RID-6cl1v6awxm S-FVw7rnt34YCS U-nowhereman] <- Socket request for "photo.getByBounds" method finished in 3009ms and responded to the client
    at async Socket.handleSocketRequest (/code/app/request.js:308:20)
    at async Object.callWebApi (/code/app/request.js:89:15)
    at async Object.callMethod [as call] (/code/app/webapi/server.js:61:62)
    at async Object.callMethod [as call] (/code/app/webapi/server.js:61:62)
    at async Object.getBounds (/code/controllers/photo.js:265:9)
    at async Object.callMethod [as call] (/code/app/webapi/server.js:61:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runMicrotasks (<anonymous>)
    at Object.getBoundsByYear (/code/controllers/cluster.js:473:29)
 TypeError: Cannot read properties of undefined (reading '1826')
}
  localWork: false
  isPainting: false,
  year2: 1990,
  year: 1826,
  startAt: 1703714630430,
  },
    }
      properties: { name: 'urn:x-mongodb:crs:strictwinding:EPSG:4326' }
      type: 'name',
    crs: {
    ],
      ]
        ... 607 more items
        [ -73.30957000000001, -2.700081 ],
        [ -74.30957000000001, -2.700081 ],
```

**Comment by kabalin** [comment]
Issue is caused by missing `y` attribute in some newly created clusters.
